# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sqlite3"
gem "sinatra"
gem "byebug"
# gem 'aether', path: '../aether' # for test in localhost
gem 'aether', git: 'git@github.com:solehudinmq/aether.git', branch: 'main'
gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"
